[profile.default]
src = "contracts"
test = "test"
script = "script"
out = "artifacts"
libs = ["node_modules", "lib"]
auto_detect_remappings = false
evm_version = "shanghai"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
