[profile.default]
src = "contracts"
test = "test"
script = "script"
out = "artifacts"
libs = ["node_modules", "lib"]
auto_detect_remappings = false
sender = "0x0f14341A7f464320319025540E8Fe48Ad0fe5aec"
evm_version = "london"
optimizer = true
optimizer_runs = 999999
extra_output = ["devdoc", "userdoc", "metadata", "storageLayout"]

fs_permissions = [
  { "access" = "read-write", "path" = "./script/output/"},
  { "access" = "read-write", "path" = "./deployments/" },
  { "access" = "read", "path" = "./script/input/"},
  { "access" = "read", "path" = "./broadcast/" },
  { "access" = "read", "path" = "./artifacts/" },
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "preserve"
single_line_statement_blocks = "preserve"
override_spacing = false
wrap_comments = false
ignore = []
contract_new_lines = false

[rpc_endpoints]
arbitrum-goerli = "https://goerli-rollup.arbitrum.io/rpc"
pangolin = "https://pangolin-rpc.darwinia.network"

[etherscan]
arbitrum-goerli = { key = "${ETHERSCAN_ARBITRUM_KEY}" }
pangolin = { key = "${ETHERSCAN_PANGOLIN_KEY}", url = "https://pangolin.api.subscan.io/api/scan/evm/contract/verifysource" }
